[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.2"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "npm", "homebrew"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Don't auto-include README, LICENSE, CHANGELOG in archives
auto-includes = false
# Allow custom modifications to the release workflow
allow-dirty = ["ci"]
# A namespace to use when publishing this package to the npm registry
npm-scope = "@reflex-search"
# A GitHub repo to push Homebrew formulas to
tap = "reflex-search/homebrew-tap"
# Publish jobs to run in CI
publish-jobs = ["npm", "homebrew"]
